---
# tasks file for logrotate

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install logrotate
  package:
    name: "{{ logrotate_packages }}"
    state: present

- name: configure logrotate
  template:
    src: "{{ logrotate_config_file }}.j2"
    dest: "{{ logrotate_config_directory }}/{{ logrotate_config_file }}"
    mode: "0644"

- name: generate logrotate.d files
  template:
    src: entry.j2
    dest: "{{ logrotate_confd_directory }}/{{ item.name }}"
    mode: "0644"
  loop: "{{ logrotate_entries }}"
  when:
    - logrotate_entries is defined
  loop_control:
    label: "{{ item.name }}"
