---
# tasks file for logrotate
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      skip: yes
  when:
    - logrotate_user is not defined
    - logrotate_group is not defined

- name: import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install logrotate
  ansible.builtin.package:
    name: "{{ logrotate_packages }}"
    state: present

- name: configure logrotate
  ansible.builtin.template:
    src: "{{ logrotate_config_file }}.j2"
    dest: "{{ logrotate_config_directory }}/{{ logrotate_config_file }}"
    mode: "0644"

- name: generate logrotate.d files
  ansible.builtin.template:
    src: entry.j2
    dest: "{{ logrotate_confd_directory }}/{{ item.name }}"
    mode: "0644"
  loop: "{{ logrotate_entries }}"
  when:
    - logrotate_entries is defined
  loop_control:
    label: "{{ item.name }}"
